name: Figures

on:
    push:
      branches:
        - main
    pull_request:

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - uses: HatsuneMiku3939/direnv-action@v1

      - name: Build figures
        run: |
          python3 src/hello.py