name: Figures

on:
    push:
      branches:
        - main
    pull_request:

jobs:
  figures:
    name: figures
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: PalisadeResearch/ci-action@master
        with:
          github_access_token: ${{ github.token }}

      - run: ninja figures