# This is essentially https://github.com/PalisadeResearch/ci-action with an emphasis on being readable by people setting up their system for the first time.
# README.md should closely track this script.
name: Setup toolchain

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  push:
    paths:
      - .github/workflows/setup-toolchain.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-toolchain:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        run: |
          sh <(curl -L https://nixos.org/nix/install) --daemon
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
          # You may add your GitHub token to Nix to avoid rate limiting.
          echo "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}" >> ~/.config/nix/nix.conf
          # GitHub Actions-specific; Nix will automatically add these to PATH.
          echo "/nix/var/nix/profiles/default/bin" >> "$GITHUB_PATH"
          echo "$HOME/.nix-profile/bin" >> "$GITHUB_PATH"

      - name: Install direnv and pre-commit
        run: |
          nix profile install nixpkgs#direnv nixpkgs#nix-direnv nixpkgs#pre-commit
          mkdir -p ~/.config/direnv
          echo 'source $HOME/.nix-profile/share/nix-direnv/direnvrc' > ~/.config/direnv/direnvrc

      - name: Nix hello world
        run: nix-shell -p hello --run "hello"

      - name: Run direnv
        run: |
          direnv allow
          # GitHub Actions-specific; direnv will trigger these on your machine automatically with its shell hook.
          direnv exec . sh -c 'echo $PATH' > "$GITHUB_PATH"
          direnv export gha >> "$GITHUB_ENV"

      - name: Run pre-commit
        run: pre-commit install && pre-commit run
