on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/type-check.yml
    - "**.py"
    - "**.pyi"
    - pyproject.toml
    - uv.lock
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 42 8 * * *

name: Type Check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    name: mypy
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: PalisadeResearch/ci-action@master
        with:
          github_access_token: ${{ github.token }}

      - name: Install dev dependencies
        run: uv sync --extra dev

      - name: Run mypy
        run: uv run mypy .